apiVersion: v1
kind: Service
metadata:
  name: gpu-metrics
  labels:
    app: node-gpu-metrics-exporter
    k8s-app: node-gpu-metrics-exporter
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http-metrics
    port: 9400
    protocol: TCP
  selector:
    app: node-gpu-metrics-exporter
